name: workroom_flutter_app
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  auth0_flutter: ^1.2.1
  bloc: ^8.1.1
  connectivity_plus: ^3.0.6
  dio: ^4.0.0
  dio_cache_interceptor: ^3.4.2
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_form_builder: ^9.0.0
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.0
  flutter_staggered_grid_view: ^0.6.2
  get_it: null
  hive: ^2.2.3
  image_picker: ^0.8.7+5
  injectable: null
  intl: ^0.18.0
  marquee: ^2.2.3
  path_provider: ^2.0.14
  rxdart: ^0.27.7
  supertokens_flutter: ^0.1.1
  timelines: ^0.1.0

dev_dependencies:
  bloc_test: ^9.1.1
  # add build runner if not already added
  build_runner: null
  flutter_test:
    sdk: flutter
  # add the generator to your dev_dependencies
  injectable_generator: null
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/work_queue_icons/
    - assets/images/
    - assets/icons/
    - assets/icons/home_screen_icons/
    - assets/icons/access_screen_icons/
    - assets/icons/auth_screen_icons/
    - assets/images/station_test_images/
  fonts:
    - family: GlacialIndifference
      fonts:
        - asset: assets/fonts/GlacialIndifference-Regular.otf
        - asset: assets/fonts/GlacialIndifference-Bold.otf
        - asset: assets/fonts/GlacialIndifference-Italic.otf
          weight: 700
